#!/bin/bash

DB2PATH="/opt/ibm/db2/V11.5"
EXTRA_LFLAG="-Wl,-rpath,${DB2PATH}/lib64"

db2 connect to stud2020 user student using abcdef

db2 precompile $1.sqC bindfile
db2 bind $1.bnd

g++ -I$DB2PATH/include -c $1.C
g++ -o $1 $1.o $EXTRA_LFLAG -L$DB2PATH/lib64 -ldb2

db2 connect reset
